eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

spring:
  cloud:
    config:
      override-system-properties: false
      fail-fast: ${SPRING_CLOUD_CONFIG_FAIL_FAST:true}
      retry:
        initial-interval: 1500
        max-attempts: 10
        max-interval: 10000
        multiplier: 1.5

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always