server:
  port: 8888

spring:
  profiles:
    active: native

  application:
    name: config-service

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
      override-system-properties: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always