spring:
  application:
    name: lucky-service

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${random.value}

  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"