server:
  port: 8080

spring:
  application:
    name: gateway-service

  config:
    import: configserver:http://config-service:8888

  cloud:
    config:
      fail-fast: true   # Config 서버 연결 실패시 애플리케이션  시작 중단
