spring:
  application:
    name: gateway-service

  # 게이트웨이 설정
  cloud:
    gateway:
      default-filters:
        - GlobalFilter

      routes:
        - id: user-serivce
          #          uri: http://localhost:8081
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

#        - id: ex2-serivce
#          uri: lb://ex2-service
#          predicates:
#            - Path=/diaries/**

server:
  port: 80

logging:
  charset:
    console: 'UTF-8'
    file: 'UTF-8'

  file:
    name: ./log/${spring.application.name}.log

  level:
    com.netflix.eureka: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG


eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # IP와 랜덤문자열을 통해 id 설정(server.port=0 사용시 동일한 id가 생성되어 random 사용)
    # instance-id: ${spring.cloud.client.ip-address}:${server.port}

  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: "http://localhost:8761/eureka/" # 유레카 서버 주소